# Generated by Django 5.1.4 on 2026-02-04 07:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_perangkat', models.CharField(max_length=100, unique=True)),
                ('nama_perangkat', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_heart_rate_bpm', models.FloatField(blank=True, null=True)),
                ('last_body_temp_c', models.FloatField(blank=True, null=True)),
                ('last_reading_time', models.DateTimeField(blank=True, null=True)),
                ('heart_status', models.CharField(blank=True, max_length=20)),
                ('temp_status', models.CharField(blank=True, max_length=20)),
                ('overall_status', models.CharField(blank=True, max_length=10)),
                ('is_valid', models.BooleanField(default=False)),
                ('last_saved_reading_time', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading', to='monitoring.device')),
            ],
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('heart_rate_bpm', models.FloatField()),
                ('body_temp_c', models.FloatField()),
                ('heart_status', models.CharField(max_length=20)),
                ('temp_status', models.CharField(max_length=20)),
                ('overall_status', models.CharField(max_length=10)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='monitoring.device')),
            ],
        ),
    ]
