# Generated by Django 5.1.4 on 2026-03-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicereading',
            name='bpm_frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devicereading',
            name='finger_detected',
            field=models.BooleanField(default=False),
        ),
    ]
